### ISSUE TITLE
(this was a mistake of me, sorry) Avatar background in Survival Mode inventory doesn't appear white like on Creative Mode Inventory

### ISSUE THREAD

**Issue by Brun333rp** [StormDragon77/Stormilla#111]
![2021-01-19_21 18 55](https://user-images.githubusercontent.com/77504298/105110132-b4398a80-5a9c-11eb-95c5-11d72b61a765.png)
![2021-01-19_21 20 42](https://user-images.githubusercontent.com/77504298/105110135-b4d22100-5a9c-11eb-8b60-0c66afde2226.png)

**Comment by StormDragon77** [comment]
I downloaded the pack on PMC and looked through the files. The inventory file is present so there might be a conflicting pack or the file is missing from yours and you'll have to redownload

**Comment by Brun333rp** [comment]
I don't think so, because the other packs I'm using don't change inventory GUI

**Comment by Brun333rp** [comment]
oh, I just checked it and it actually was that. sorry about this :(
