### ISSUE TITLE
Change the Silverfish and Endermite textures to more resemble real life silverfishes and mites

### ISSUE THREAD

**Issue by Brun333rp** [StormDragon77/Stormilla#150]
Maybe just texture changes, or model changes if optifine is enabled. Here I put some pictures as examples, but you can search for more pictures if you prefer.

![image](https://user-images.githubusercontent.com/77504298/108542420-78bff500-72c2-11eb-88bc-6abda55fd177.png) ![image](https://user-images.githubusercontent.com/77504298/108542848-07347680-72c3-11eb-8788-ada2fb022b5f.png)

![image](https://user-images.githubusercontent.com/77504298/108542714-d81e0500-72c2-11eb-9c94-6f04c56459f9.png) ![image](https://user-images.githubusercontent.com/77504298/108542965-28956280-72c3-11eb-876e-b9fa60940044.png)

**Comment by StormDragon77** [comment]
Related: #60

**Comment by Brun333rp** [comment]
just a tip: while they could resemble their real life counterparts, they should still using the original colors. for instance, the real life silverfish has yellow legs and antennas, but it should still having grey as their color, similar to the "fur" on their backs.
