### ISSUE TITLE
Change Painting borders and item to resemble spruce wood

### ISSUE THREAD

**Issue by Brun333rp** [StormDragon77/Stormilla#151]
The back texture resembles spruce planks, so to make it consistent, change the border and item textures to resemble spruce as well.

**Comment by StormDragon77** [comment]
Related: #27

**Comment by VictoriousMaverick** [comment]
![IMG_20220401_125511](https://user-images.githubusercontent.com/90498980/161198374-343e209a-6ab4-421d-aa58-9cc37a31c9c1.jpg)
Item hasn't been changed, the borders should resemble spruce

Applies to Bedrock and Java
