### ISSUE TITLE
Add forgotten JAPPA dirt.

### ISSUE THREAD

**Issue by sadlittletree** [StormDragon77/Stormilla#232]
![DFFSKXlXsAEGCaX](https://user-images.githubusercontent.com/81985011/118717045-2623a580-b7eb-11eb-9e63-ee58c5da58d7.jpeg)
On this footage, there's a forgotten dirt, which it has been confirmed by JAPPA that this was for testing.

**Comment by StormDragon77** [comment]
Will make a texture instead of using the beta one
