### ISSUE TITLE
Update Nether Gold Ore Texture With 1.17's Gold Ore Texture

### ISSUE THREAD

**Issue by Kancer8496** [StormDragon77/Stormilla#252]
The nether gold ore's texture has to be updated with 1.17's gold ore texture like this:
![nether_gold_ore](https://user-images.githubusercontent.com/85027438/120583686-4d23dd80-c461-11eb-95d2-8e5d0165f4cf.png)

**Comment by sadlittletree** [comment]
https://twitter.com/JasperBoerstra/status/1362396724493504518
This is why nether gold ore wasn't changed in 1.17, after the former ore change.

**Comment by Brun333rp** [comment]
no, it shouldn't be changed because it works differently from Overworld gold

**Comment by StormDragon77** [comment]
Closed for reasons above
