### ISSUE TITLE
Using double slabs flips the texture.

### ISSUE THREAD

**Issue by InhumanNebula56** [StormDragon77/Stormilla#260]
I am Using Stormilla but when I place 2 double slabs of any kind the bottom texture is flipped vertically

Place a double oak slab and a single bottom near it.

![2021-06-16_14 56 42](https://user-images.githubusercontent.com/74444183/122195783-49a64280-ceb4-11eb-9565-7a49e671df40.png)

Uploading Minecraft 1.16.5 - Singleplayer 2021-06-16 14-59-43.mp4…

Java 1.16.5

**Comment by StormDragon77** [comment]
fixed
