### ISSUE TITLE
Tamed Cat Rendering/Texture Issue?

### ISSUE THREAD

**Issue by TheMythMoth** [StormDragon77/Stormilla#287]
**Describe the bug**
Apologies if I use the wrong terms and such, I am not particularly tech savvy. The bug in question I believe is either a rendering or texture issue with a specific variant of the tamed cat entities. Their models load incorrectly and their form is incomplete for lack of a better words.

**To Reproduce**
Steps to reproduce the behavior: (I apologize again here, I'm not sure what this question is asking? ;-;)

**Expected behavior**
Just for the cats to load properly. It isn't a huge issue since everything else seems great however I figured it would be good to let you guys know!

**Screenshots**
The image is a bit poor quality but I've added the file by dragging it below so here's the visual bug on the cats. (Hopefully the link works!)

**Mods? Resource Packs?**
None aside from the default Minecraft textures! I had an 'updated texture pack' installed that's from Minecraft as well but I deactivated it and checked to be sure that it wasn't the cause and it wasn't.

**Game version**
This is on Windows 10 Bedrock Edition! To my knowledge the game is also fully updated.

**Additional context**
If you need more info, more images, or have questions on anything that may not have been clear, feel free to shoot me a Discord dm at TheMythMoth#8181 ! Or just to let me know if I am dumb and made a mistake somewhere that's causing this.
![cat texture bug](https://user-images.githubusercontent.com/88219912/127727075-9965ce6d-3a1c-4f86-9808-da56d971215d.jpg)

**Comment by StormDragon77** [comment]
Hi thanks for reporting, looks like a texture issue caused by an error I made while making the texture and I think I'll get a bug fix release to fix this since it's a very noticeable problem.

Also the reproduce section is just to describe how to get the bug to show up. It's really only there for complicated bugs or ones that are hard to replicate.

**Comment by StormDragon77** [comment]
Fixed!
