### ISSUE TITLE
Farmland sides not working

### ISSUE THREAD

**Issue by VictoriousMaverick** [StormDragon77/Stormilla#316]
They do not appear.
![Screenshot_2021-10-13-12-11-28-00](https://user-images.githubusercontent.com/90498980/137093089-f6ded3d4-22c7-487c-9225-4205d83ecdb7.png)

Bedrock Edition 1.17.30

**Comment by StormDragon77** [comment]
fixed

**Comment by VictoriousMaverick** [comment]
I can't see it
![Screenshot_2022-01-18-00-28-16-36](https://user-images.githubusercontent.com/90498980/149870767-d605f124-8a78-43d0-a564-939dc8584cbf.png)

**Comment by StormDragon77** [comment]
![Minecraft 1_17_2022 9_32_54 PM](https://user-images.githubusercontent.com/73137110/149871568-235ccfa6-56ff-41ad-925e-39dd33b6f135.png)

it is working for me, I updated the file again
