### ISSUE TITLE
Strider missing a leg

### ISSUE THREAD

**Issue by VictoriousMaverick** [StormDragon77/Stormilla#320]
![20211019_113628](https://user-images.githubusercontent.com/90498980/137840725-ce5a7c27-bf97-4f50-a6be-db9544c6a934.png)
The first strider is cold and missing a leg, it's still missing with or without saddle.
The second strider seems fine and is on lava, It has no saddle on.
The third strider is on lava, but with saddle applied and is missing a leg.

Bedrock Edition 1.17.30

**Comment by StormDragon77** [comment]
fixed
