### ISSUE TITLE
Inconsistent Ender Chest lock

### ISSUE THREAD

**Issue by VictoriousMaverick** [StormDragon77/Stormilla#323]
I know it's fixed, but in my perspective, it just doesn't look right compared to the gold block and gold ingot.
![Screenshot_2021-10-21-18-39-15-12](https://user-images.githubusercontent.com/90498980/138396485-b063a856-eada-43a8-8951-7e0185b15420.png)
Bedrock Edition 1.17.30

**Comment by StormDragon77** [comment]
Fixed, was using old version of palette. Will be in 2.2
