### ISSUE TITLE
Better fence textures

### ISSUE THREAD

**Issue by StormDragon77** [StormDragon77/Stormilla#347]
Give a custom texture to make the planks logically follow the cubes of the model instead of just pasting the planks texture on.

Original Idea from burg3er on discord server

**Comment by Nebby-56** [comment]
I personally dislike the log fences so will it be an addon or something?

**Comment by StormDragon77** [comment]
maybe? I'm planning on using the stripped log textures so the fences stay the same color and don't change builds too much.
