### ISSUE TITLE
Missing stripped dark oak wood texture from Java

### ISSUE THREAD

**Issue by VictoriousMaverick** [StormDragon77/Stormilla#356]
Might consider adding them to the bedrock version, because the developers can't add them yet.
![Screenshot_2022-01-17-12-51-23-07](https://user-images.githubusercontent.com/90498980/149711491-bbf5eb78-fe4b-4070-897a-eb1537003d7b.png)

**Comment by StormDragon77** [comment]
it was already added, the java texture is pretty much just slightly brighter than the bedrock one
