### ISSUE TITLE
End sky bug

### ISSUE THREAD

**Issue by VictoriousMaverick** [StormDragon77/Stormilla#366]
End sky's stars can barely be seen and is more greyish than purple (with night vision)

Without night vision
![Screenshot_2022-01-18-17-09-09-43](https://user-images.githubusercontent.com/90498980/149921056-71f23c48-c2da-47d6-8fe0-df8357cfc593.png)
With night vision
![Screenshot_2022-01-18-17-10-06-16](https://user-images.githubusercontent.com/90498980/149921099-ea9d37b7-db08-4c2a-a22d-a320389d0003.png)

Close-up look of the stars
![Screenshot_2022-01-18-17-11-58-08](https://user-images.githubusercontent.com/90498980/149921162-c20f5f36-7c60-469c-9c38-49d22cb03b07.png)

Bedrock Edition 1.18.2

**Comment by StormDragon77** [comment]
I don't think there is anything I can do about this. It is also really dark and grayer in vanilla
