### ISSUE TITLE
Texture typos

### ISSUE THREAD

**Issue by VictoriousMaverick** [StormDragon77/Stormilla#369]
Found on the pack

"redstone_dust_linee"
![Screenshot_2022-01-18-23-40-58-78](https://user-images.githubusercontent.com/90498980/149969340-f87361e7-191a-450a-9e43-f5649fde94ec.png)

"chest_side_@"
![Screenshot_2022-01-19-09-13-08-42](https://user-images.githubusercontent.com/90498980/150044990-5e6e4660-5091-41df-9b29-0b1f1f63c108.png)

Bedrock 1.18.2

**Comment by StormDragon77** [comment]
chest_side_@ and the other labeled 2 are just left over from development so they'll just be removed.
