### ISSUE TITLE
Stormilla based panaromas

### ISSUE THREAD

**Issue by SiDjackWasTaken** [StormDragon77/Stormilla#394]
Make Stormilla based panaromas. They will still show off updates (eg. 1.18, 1.17 etc) but they will have Stormilla textures. This could also allow for add ons that have old backgrounds (1.17, 1.16, 1.15, 1.14, 1.13 & pre 1.13).

**Comment by StormDragon77** [comment]
Added for 1.19 and will add for future updates, don't think I'll add ones for previous updates tho
