### ISSUE TITLE
Outdated and missing textures from 2.3 

### ISSUE THREAD

**Issue by VictoriousMaverick** [StormDragon77/Stormilla#407]
![IMG_20220331_174422](https://user-images.githubusercontent.com/90498980/161026937-48a93e28-010e-434e-8554-837654c43d67.jpg)
New ender chest, end eye and portal texture are missing, as well as the book on the enchantment table.

![IMG_20220331_112716](https://user-images.githubusercontent.com/90498980/161027362-db0c8d3e-7ebb-46e8-b2a7-53c0569f2d45.jpg)
Outdated ender chest item texture, soul lantern item texture has turquoise colors and soul torch is inconsistent with the look of torches (redstone torch and normal torch) from 2.2

![IMG_20220331_112803](https://user-images.githubusercontent.com/90498980/161027889-6bc8edcd-ab41-4d15-be02-2e09593b9de1.jpg)
New soul particle is missing

Where is spore blossom item texture?

Bedrock Edition 1.18.12

**Comment by StormDragon77** [comment]
the purple enchanting table book was left out because that would also change the book on the lectern
with the spore blossom, I just forgot to take that out of the image since it can't be added
everything else fixed
