### ISSUE TITLE
Stretched experience bar 

### ISSUE THREAD

**Issue by VictoriousMaverick** [StormDragon77/Stormilla#412]
![IMG_20220405_131224](https://user-images.githubusercontent.com/90498980/161683551-349b6918-3738-4128-b2a8-1cab4fdeab4f.jpg)
This is what the bedrock edition normally does with the experience bar, but the appearance isn't so similar to Java as I expected. This does not affect the horse bar.

Bedrock Edition 1.18.12

**Comment by StormDragon77** [comment]
just fixed, probably gonna release a patch tonight
