### ISSUE TITLE
Shield appears too high in-game and in GUI

### ISSUE THREAD

**Issue by K0JINKINZ0** [StormDragon77/Stormilla#531]
Using Fabric with mods. (specifically the Fabulously Optimized modpack) Shield appears to be busted in-game and covers the whole right side of the screen and appears wrong on player model. It also appears slightly higher in the GUI and inventory HUD as well.

![2024-10-16_20 06 35](https://github.com/user-attachments/assets/c4c2e8af-7a0c-458f-a15e-d37ccc4801a0)
![2024-10-16_20 06 48](https://github.com/user-attachments/assets/ba6518e1-7085-4056-99ab-6cc2e7720423)
![2024-10-16_20 07 00](https://github.com/user-attachments/assets/f406b4b9-b276-49b4-b304-d46953a2ff2d)

**Comment by StormDragon77** [comment]
turns out I have fixed this but it requires the Respackopts mod
in the pack settings with the mod, go to Mod Compatibility and set EMF Fixes to True
